### ISSUE TITLE
Items that are applied to foxes via right-click do not apply and instead cause desync problems

### ISSUE THREAD

**Issue by Febilian** [ItsTheKais/Outfox#1]
To clarify:

Heat and Climate is a Japanese mod that was recently put on Curseforge. It adds a handful of "Amulet" items that can be applied to pets one at a time by right clicking to give them various boons, such as immunity to bad potion effects, immunity to environmental damage, etc. To give them to pets, you can either put them into a valid inventory attached to the pet/creature(such as with donkeys/mules), or in the case of pets that don't have one(like cats and wolves, and in this case, foxes), right click them with the amulet.

I tried giving one of these amulets to a fox I tamed because I wanted to protect my adorable new friend(who wouldn't?), but it will not accept the amulet - I assume this has something to do with the "right click the fox with a block to have them search for it" feature, as the fox appears to consume the amulet at first glance, but then if you click on the inventory/hotbar slot the amulet was previously, it's still there, and not on the fox.

The amulets work fine on tamed ocelots(and so I assume wolves), and they properly apply to pets from another mod I have installed, Kindred Legacy, so it seems to be a fox-specific issue.

Please let me know if there is more information that I could provide to assist in resolving this(if possible).

**Comment by Febilian** [comment]
Update: Any item that utilizes right-click is overridden. I cannot use a nametag from vanilla on my fox either; it appears clientside but upon relogging it reverts, and other players cannot see the name. I also got my nametag back.

**Comment by ItsTheKais** [comment]
Should be fixed in 0.1.1. Let me know if there are still any problems.
