### ISSUE TITLE
foxes wont tame

### ISSUE THREAD

**Issue by Evilteen18** [ItsTheKais/Outfox#2]
ok with pams harvestcraft mod install i cant tame the foxes they wont tame at all i waited and click many times they just look up at me and nothing

**Comment by ItsTheKais** [comment]
I'm unable to reproduce on my end. Make sure you're using vanilla raw rabbit (/give @p minecraft:rabbit) and, if you're in survival mode, wait until the fox walks up to you and stops. If you see smoke or heart particles, it's working correctly. If you're still having trouble, pastebin your minecraft.log after trying to tame a fox.
